# Generated by Django 4.0.3 on 2022-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post_duedate_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duedate',
            field=models.DateTimeField(default=False),
        ),
    ]
