# Generated by Django 4.0.4 on 2022-05-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
